version: "3.8"

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: app
    environment:
      - ./app/.env
    ports:
      - "8000:8000"
    networks:
      - fastapi-demo-network

  movie:
    build:
      context: ./movie
      dockerfile: Dockerfile
    container_name: movie
    environment:
      - ./movie/.env
    ports:
      - "8001:8001"
    networks:
      - fastapi-demo-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    depends_on:
      - app
      - movie
    restart: always
    ports:
      - "3050:80"
    networks:
      - fastapi-demo-network

  apisix:
    image: apache/apisix:latest
    volumes:
      - ./apisix/config.yml:/usr/local/apisix/conf/config.yaml:ro
      - ./apisix/apisix.yml:/usr/local/apisix/conf/apisix.yaml:ro
      - ./logs:/usr/local/apisix/logs
    depends_on:
      - nginx
      - elasticsearch
    ports:
      - "9080:9080"
    environment:
      - GATEWAY_PORT=9080
    networks:
      - fastapi-demo-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ELASTIC_PASSWORD=changeme
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - fastapi-demo-network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.1
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=changeme
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    networks:
      - fastapi-demo-network

networks:
  fastapi-demo-network:
    driver: bridge
