version: "3.8"

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: app
    environment:
      - ./app/.env
    ports:
      - "8000:8000"
    networks:
      - fastapi-demo-network

  movie:
    build:
      context: ./movie
      dockerfile: Dockerfile
    container_name: movie
    environment:
      - ./movie/.env
    ports:
      - "8001:8001"
    networks:
      - fastapi-demo-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    depends_on:
      - app
      - movie
    restart: always
    ports:
      - "3050:80"
    networks:
      - fastapi-demo-network

  apisix:
    image: apache/apisix:latest
    volumes:
      - ./apisix/config.yml:/usr/local/apisix/conf/config.yaml:ro
      - ./apisix/apisix.yml:/usr/local/apisix/conf/apisix.yaml:ro
      - ./logs:/usr/local/apisix/logs
    depends_on:
      - nginx
    ports:
      - "9080:9080"
    environment:
      - GATEWAY_PORT=9080
    networks:
      - fastapi-demo-network

networks:
  fastapi-demo-network:
    driver: bridge
