version: '3.8'

services:

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: app_service
    environment:
      - ./app/.env
    ports:
      - "8000:8000"

  movie:
    build:
      context: ./movie
      dockerfile: Dockerfile
    container_name: movie_service
    environment:
      - ./movie/.env
    ports:
      - "8001:8001"
