version: "3.8"

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: app
    environment:
      - ./app/.env
    ports:
      - "8000:8000"
    networks:
      - apisix
    labels:
      - "dapr.io/enabled=true"
      - "dapr.io/app-id=app"
      - "dapr.io/app-port=8000"
      - "dapr.io/sidecar-http-port=3500"
      - "dapr.io/sidecar-grpc-port=50001"

  movie:
    build:
      context: ./movie
      dockerfile: Dockerfile
    container_name: movie
    environment:
      - ./movie/.env
    ports:
      - "8001:8001"
    networks:
      - apisix
    labels:
      - "dapr.io/enabled=true"
      - "dapr.io/app-id=movie"
      - "dapr.io/app-port=8001"
      - "dapr.io/sidecar-http-port=3501"
      - "dapr.io/sidecar-grpc-port=50002"

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    depends_on:
      - app
      - movie
    restart: always
    ports:
      - "3050:80"
    networks:
      - apisix

  app-dapr:
    image: "daprio/daprd:edge"
    command:
      [
        "./daprd",
        "-app-id",
        "app",
        "-app-port",
        "8000",
        "-placement-host-address",
        "placement:50006",
        "-dapr-grpc-port",
        "50001",
        "-dapr-http-port",
        "3500",
        "-components-path",
        "/components",
      ]
    volumes:
      - "./components/:/components"
    depends_on:
      - app
    ports:
      - "3500:3500" # Dapr HTTP port
      - "50001:50001" # Dapr gRPC port
    networks:
      - apisix

  movie-dapr:
    image: "daprio/daprd:edge"
    command:
      [
        "./daprd",
        "-app-id",
        "movie",
        "-app-port",
        "8001",
        "-placement-host-address",
        "placement:50006",
        "-dapr-grpc-port",
        "50002",
        "-dapr-http-port",
        "3501",
        "-components-path",
        "/components",
      ]
    volumes:
      - "./components/:/components"
    depends_on:
      - movie
    ports:
      - "3501:3501" # Dapr HTTP port
      - "50002:50002" # Dapr gRPC port
    networks:
      - apisix

  apisix:
    image: apache/apisix:latest
    volumes:
      - ./apisix/config.yml:/usr/local/apisix/conf/config.yaml:ro
      - ./apisix/apisix.yml:/usr/local/apisix/conf/apisix.yaml:ro
      - ./logs:/usr/local/apisix/logs
    depends_on:
      - nginx
    ports:
      - "9080:9080"
    environment:
      - GATEWAY_PORT=9080
    networks:
      - apisix

  placement:
    image: "daprio/dapr:edge"
    command: ["./placement", "-port", "50006"]
    ports:
      - "50006:50006"
    networks:
      - apisix

  redis:
    image: "redis:alpine"
    ports:
      - "6380:6379"
    networks:
      - apisix

networks:
  apisix:
    driver: bridge
