version: "3.8"

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: app_service
    environment:
      - ./app/.env
    ports:
      - "8000:8000"
    networks:
      - fastapi-demo-network

  movie:
    build:
      context: ./movie
      dockerfile: Dockerfile
    container_name: movie_service
    environment:
      - ./movie/.env
    ports:
      - "8001:8001"
    networks:
      - fastapi-demo-network

  placement:
    image: "daprio/dapr"
    command: ["./placement", "--port", "50006"]
    ports:
      - "50006:50006"

networks:
  fastapi-demo-network:
    driver: bridge
