# Use the official Elasticsearch image as the base image
FROM elasticsearch:8.8.2

# Set environment variables
ENV discovery.type=single-node

# Expose the necessary ports
EXPOSE 9200 9300

# Command to run Elasticsearch
CMD ["elasticsearch"]
