apisix:
  extra_lua_path: "/opt/apisix/plugins/*.lua"

deployment:
  role: data_plane
  role_data_plane:
    config_provider: yaml

plugins:
  - jwt-auth
  - file-logger
  - request-logger
  - add-header
  - forward-auth

plugin_attr:
  file-logger:
    path: "/usr/local/apisix/logs/access.log"

  jwt-auth:
    key: "Secret"
    algorithm: "HS256"
