deployment:
  role: data_plane
  role_data_plane:
    config_provider: yaml

plugins:
  - jwt-auth

plugin_attr:
  file-logger:
    path: "/usr/local/apisix/logs/access.log"

  jwt-auth:
    key: "Secret"
    algorithm: "HS256"

