apisix:
  enable_ipv6: false

  enable_control: true
  control:
    ip: "0.0.0.0"
    port: 9092

deployment:
  role: data_plane
  role_data_plane:
    config_provider: yaml

plugins:
  - jwt-auth
  - request-logger

plugin_attr:
  file-logger:
    path: "/usr/local/apisix/logs/access.log"

  jwt-auth:
    key: "Secret"
    algorithm: "HS256"

